import type { ContentBundle } from '../bundle.ts';
import { formatIssue } from './compile.ts';

/** Markdown renderers for the generated matrices (spec §137–§138): reports, never hand-kept. */

function table(header: string[], rows: string[][]): string {
  const line = (cells: string[]) => `| ${cells.join(' | ')} |`;
  return [line(header), line(header.map(() => '---')), ...rows.map(line)].join('\n');
}

export function renderContentCoverage(bundle: ContentBundle): string {
  const rows = bundle.coverage.content.map((row) => [
    `\`${row.skill}\``,
    row.territory,
    String(row.learn),
    String(row.guided),
    String(row.practice),
    String(row.fix),
    String(row.independent),
    String(row.pressure),
    String(row.fieldwork),
    String(row.sales_use),
    row.gaps.length ? row.gaps.join(', ') : '—',
  ]);
  return [
    `# Content coverage — content ${bundle.content_version}`,
    '',
    'Generated by the content compiler (spec §137, CUR-033). Counts are learning units (Learn) and exercises per column. "Gaps" lists what the skill\'s mastery requirements demand but no content provides.',
    '',
    table(
      [
        'Skill',
        'Territory',
        'Learn',
        'Guided',
        'Practice',
        'Fix',
        'Independent',
        'Pressure',
        'Fieldwork',
        'Sales Use',
        'Gaps',
      ],
      rows,
    ),
    '',
  ].join('\n');
}

export function renderGhlCoverage(bundle: ContentBundle): string {
  const rows = bundle.coverage.ghl.map((row) => [
    `\`${row.feature}\``,
    row.official_name,
    row.status,
    row.fidelity,
    row.simulator ? 'yes' : 'no',
    row.skills.length ? row.skills.map((s) => `\`${s}\``).join(', ') : '—',
    row.exercises.length ? row.exercises.map((e) => `\`${e}\``).join(', ') : '—',
    row.fieldwork.length ? row.fieldwork.map((e) => `\`${e}\``).join(', ') : '—',
    row.last_verified,
  ]);
  return [
    `# GHL coverage — content ${bundle.content_version}`,
    '',
    'Generated by the content compiler (spec §138, GHL-007). "Simulator" means a simulator exercise or scenario workflow uses the feature, so the Workflow Lab must offer it.',
    '',
    table(
      [
        'Feature',
        'Official name',
        'Status',
        'Fidelity',
        'Simulator',
        'Skills',
        'Exercises',
        'Fieldwork',
        'Last verified',
      ],
      rows,
    ),
    '',
  ].join('\n');
}

export function renderFreshness(bundle: ContentBundle): string {
  const rows = bundle.freshness.map((row) => [
    `\`${row.feature}\``,
    row.official_name,
    row.status,
    row.last_verified,
    String(row.days_since_verified),
    row.reason,
  ]);
  return [
    `# GHL registry review list — content ${bundle.content_version}`,
    '',
    'Generated by the content compiler (spec §151, GHL-008): needs_review, deprecated, removed, stale or future-dated verification records. Statuses are preserved, never upgraded automatically. Run content:freshness for a dated maintenance report with sources and limitations.',
    '',
    rows.length
      ? table(['Feature', 'Official name', 'Status', 'Last verified', 'Days', 'Reason'], rows)
      : 'Nothing to review.',
    '',
  ].join('\n');
}

export function renderSummary(bundle: ContentBundle): string {
  const counts = Object.entries(bundle.counts)
    .map(([type, count]) => `${type} ${count}`)
    .join(' · ');
  const lines = [
    `content ${bundle.content_version} (${bundle.content_hash.slice(0, 12)}) — ${counts}`,
    `skill graph: ${bundle.graph.order.length} skills, max depth ${Math.max(0, ...Object.values(bundle.graph.depth))}, territories with skills ${Object.values(bundle.graph.territories).filter((list) => list.length > 0).length}/10`,
    `coverage gaps: ${bundle.coverage.content.filter((row) => row.gaps.length > 0).length} skills · registry review list: ${bundle.freshness.length}`,
  ];
  if (bundle.warnings.length > 0) {
    lines.push(`${bundle.warnings.length} warning${bundle.warnings.length === 1 ? '' : 's'}:`);
    lines.push(...bundle.warnings.map(formatIssue));
  }
  return lines.join('\n');
}
