/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings src/bindings.d.ts` (hash: 0759d3e84657df16bbf3275bcf4dcbb2)
interface __BaseEnv_CloudflareBindings {
  MEDIA: R2Bucket;
  DB: D1Database;
  ASSETS: Fetcher;
  BLOOMLAB_ENV: 'preview' | 'production' | 'local';
  SYNC_KEY_PEPPER?: string;
  ANTHROPIC_API_KEY?: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
  }
  interface PreviewEnv {
    MEDIA: R2Bucket;
    DB: D1Database;
    ASSETS: Fetcher;
    BLOOMLAB_ENV: 'preview';
    SYNC_KEY_PEPPER: string;
    ANTHROPIC_API_KEY: string;
  }
  interface ProductionEnv {
    MEDIA: R2Bucket;
    DB: D1Database;
    ASSETS: Fetcher;
    BLOOMLAB_ENV: 'production';
    SYNC_KEY_PEPPER: string;
    ANTHROPIC_API_KEY: string;
  }
  interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'BLOOMLAB_ENV' | 'SYNC_KEY_PEPPER' | 'ANTHROPIC_API_KEY'>
  > {}
}
