import { useCallback, useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router';

import { Button, Stack, Surface } from '@bloomlab/design-system';
import {
  SimulatorError,
  advance,
  allowedActions,
  contentEventName,
  historyHash,
  injectAction,
  nextEvent,
  nextScheduled,
  replay,
  rewind,
  validateScenario,
  type SimulatorScenario,
  type SimulatorState,
} from '@bloomlab/simulator-core';

import { content } from '../content/bundle';
import {
  commitRun,
  listRuns,
  loadRun,
  markCheckpoint,
  resetStoredRun,
  startRun,
  type StoredRun,
} from '../simulator/store';
import styles from './SimulatorHarness.module.css';

/**
 * The simulator harness (Phase 10). A developer surface behind the `system_diagnostics` flag, not
 * a Lab and not a learner-facing screen: it exists so the engine can be inspected by a person
 * rather than only by tests.
 *
 * Everything on this page comes out of the real engine. There is no canned data generated in
 * React, and no state kept here that the simulator does not own — every control runs a pure
 * transition and then persists whatever it produced.
 */

/**
 * Only scenarios the engine can actually run. A roleplay scenario (a discovery call, an
 * outside-in audit) is authored in the same shape but its events belong to the Call Room, not to
 * the simulated account — offering it here would present a run that cannot start.
 */
const scenarios = (content.scenarios as unknown as SimulatorScenario[]).filter(
  (candidate) => validateScenario(candidate).length === 0,
);

/** Plain words for an event's origin; the log never relies on colour alone to say this. */
const ORIGIN_WORDS: Record<string, string> = {
  scenario: 'Scheduled by the scenario',
  injected: 'Injected',
  generated: 'Generated by the engine',
  clock: 'Clock',
};

const KIND_WORDS: Record<string, string> = {
  trigger: 'Trigger',
  input: 'Input',
  step_started: 'Step started',
  step_completed: 'Step completed',
  branch_result: 'Branch result',
  action_skipped: 'Action skipped',
  waiting: 'Waiting',
  failure: 'Failure',
  exit: 'Exit',
};

const describe = (error: unknown): string =>
  error instanceof SimulatorError
    ? `${error.message} (${error.code})`
    : error instanceof Error
      ? error.message
      : 'Something went wrong.';

export default function SimulatorHarness() {
  // The scenario lives in the URL so a reload comes back to the run being inspected rather than
  // to the first one in the list — which is what makes "does this survive a reload?" answerable.
  const [params, setParams] = useSearchParams();
  const scenarioId = params.get('scenario') ?? scenarios[0]?.id ?? '';
  const setScenarioId = (id: string) => setParams({ scenario: id }, { replace: true });
  // The loaded run carries the scenario it belongs to, so "still loading" is derived rather than
  // set from inside the effect that does the loading.
  const [loaded, setLoaded] = useState<{ scenarioId: string; run: StoredRun } | null>(null);
  const [problem, setProblem] = useState<string | null>(null);
  const [replayResult, setReplayResult] = useState<string | null>(null);

  const scenario = scenarios.find((candidate) => candidate.id === scenarioId) ?? scenarios[0];
  const run = loaded && loaded.scenarioId === scenario?.id ? loaded.run : null;

  const logFailure = useCallback((error: unknown) => setProblem(describe(error)), []);
  const store = useCallback(
    (next: StoredRun) => setLoaded({ scenarioId: next.state.scenario_id, run: next }),
    [],
  );

  // Resume the newest saved run of this scenario, or start one. A reload lands where it left off.
  useEffect(() => {
    if (!scenario) return;
    let cancelled = false;
    (async () => {
      const saved = await listRuns();
      const existing = saved.find((row) => row.scenario_id === scenario.id);
      const resumed = existing ? await loadRun(existing.run_id) : null;
      const next = resumed ?? (await startRun(scenario));
      if (cancelled) return;
      setReplayResult(null);
      setProblem(null);
      setLoaded({ scenarioId: scenario.id, run: next });
    })().catch((error: unknown) => {
      if (!cancelled) logFailure(error);
    });
    return () => {
      cancelled = true;
    };
  }, [scenario, logFailure]);

  /** Runs one pure transition and persists what it produced. */
  const operate = useCallback(
    (work: (state: SimulatorState) => SimulatorState) => {
      if (!run) return;
      setProblem(null);
      setReplayResult(null);
      try {
        const next = { ...run, state: work(run.state) };
        store(next);
        void commitRun(next).then(store).catch(logFailure);
      } catch (error) {
        setProblem(describe(error));
      }
    },
    [run, store, logFailure],
  );

  if (!run || !scenario) {
    return (
      <Stack as="section" gap={3} className={styles.screen} aria-labelledby="simulator-title">
        <h1 id="simulator-title" className={styles.title}>
          Simulator
        </h1>
        <p className={styles.lead}>{problem ?? 'Loading the run…'}</p>
      </Stack>
    );
  }

  const state = run.state;
  const account = state.account;
  const upcoming = nextScheduled(state);
  const actions = allowedActions(scenario);

  const counts: [string, number][] = [
    ['Contacts', Object.keys(account.contacts).length],
    ['Opportunities', Object.keys(account.opportunities).length],
    ['Appointments', Object.keys(account.appointments).length],
    ['Conversations', Object.keys(account.conversations).length],
    ['Payments', Object.keys(account.payments).length],
    ['Workflows', Object.keys(account.workflows).length],
    ['Workflow runs', Object.keys(account.workflow_runs).length],
  ];

  return (
    <Stack as="section" gap={4} className={styles.screen} aria-labelledby="simulator-title">
      <p className={styles.back}>
        <Link to="/system" className={styles.link}>
          Back to system
        </Link>
      </p>
      <div>
        <h1 id="simulator-title" className={styles.title}>
          Simulator
        </h1>
        <p className={styles.lead}>
          The shared simulated account, driven by the real engine. Nothing on this page is generated
          by the interface.
        </p>
      </div>

      <Surface tone="snow" padding="md">
        <div className={styles.runBar}>
          <label className={styles.field}>
            <span className={styles.fieldLabel}>Scenario</span>
            <select
              className={styles.select}
              value={scenario.id}
              onChange={(changed) => setScenarioId(changed.target.value)}
            >
              {scenarios.map((candidate) => (
                <option key={candidate.id} value={candidate.id}>
                  {candidate.title ?? candidate.id}
                </option>
              ))}
            </select>
          </label>
          <dl className={styles.facts}>
            <div>
              <dt>Simulator time</dt>
              <dd>{state.clock.now}</dd>
            </div>
            <div>
              <dt>Timezone</dt>
              <dd>{state.clock.timezone}</dd>
            </div>
            <div>
              <dt>Seed</dt>
              <dd>
                {state.random.seed} · {state.random.draws} draws
              </dd>
            </div>
            <div>
              <dt>Engine</dt>
              <dd>{state.version}</dd>
            </div>
          </dl>
        </div>
      </Surface>

      {problem && (
        <Surface tone="snow" padding="md" className={styles.problem} role="alert">
          <p className={styles.problemTitle}>The engine refused that.</p>
          <p className={styles.problemBody}>{problem}</p>
        </Surface>
      )}

      <Surface tone="snow" padding="md">
        <h2 className={styles.sectionTitle}>Time machine</h2>
        <p className={styles.help}>
          {upcoming
            ? `Next scheduled: ${contentEventName(upcoming.type)} at ${upcoming.at}.`
            : 'Nothing is scheduled.'}
        </p>
        <div className={styles.controls}>
          <Button
            variant="secondary"
            onClick={() => operate((current) => advance(current, 'minute'))}
          >
            +1 minute
          </Button>
          <Button
            variant="secondary"
            onClick={() => operate((current) => advance(current, 'hour'))}
          >
            +1 hour
          </Button>
          <Button variant="secondary" onClick={() => operate((current) => advance(current, 'day'))}>
            +1 day
          </Button>
          <Button
            variant="secondary"
            disabled={!upcoming}
            onClick={() => operate((current) => nextEvent(current))}
          >
            Next event
          </Button>
        </div>
      </Surface>

      <Surface tone="snow" padding="md">
        <h2 className={styles.sectionTitle}>Event injector</h2>
        <p className={styles.help}>
          Only what this scenario allows. The engine can express far more; the scenario decides.
        </p>
        <div className={styles.controls}>
          {actions.map((action) => (
            <Button
              key={action.id}
              variant="secondary"
              onClick={() => operate((current) => injectAction(current, scenario, action.id))}
            >
              {action.description}
            </Button>
          ))}
          {actions.length === 0 && <p className={styles.help}>This scenario allows none.</p>}
        </div>
      </Surface>

      <Surface tone="snow" padding="md">
        <h2 className={styles.sectionTitle}>Account</h2>
        <dl className={styles.facts}>
          {counts.map(([label, value]) => (
            <div key={label}>
              <dt>{label}</dt>
              <dd>{value}</dd>
            </div>
          ))}
        </dl>
        <h3 className={styles.subTitle}>Contacts</h3>
        <ul className={styles.rows}>
          {Object.values(account.contacts).map((contact) => (
            <li key={contact.id} className={styles.row}>
              <span className={styles.rowName}>
                {contact.first_name} {contact.last_name ?? ''}
              </span>
              <span className={styles.rowDetail}>
                {contact.tags.length > 0 ? contact.tags.join(', ') : 'no tags'}
                {contact.dnd ? ' · do not disturb' : ''}
                {contact.phone ? '' : ' · no phone'}
              </span>
            </li>
          ))}
        </ul>
      </Surface>

      <Surface tone="snow" padding="md">
        <h2 className={styles.sectionTitle}>Scheduled events</h2>
        {state.queue.length === 0 ? (
          <p className={styles.help}>The queue is empty.</p>
        ) : (
          <ol className={styles.rows}>
            {state.queue.map((entry) => (
              <li key={entry.id} className={styles.row}>
                <span className={styles.rowName}>{contentEventName(entry.type)}</span>
                <span className={styles.rowDetail}>
                  {entry.at}
                  {entry.description ? ` · ${entry.description}` : ''}
                </span>
              </li>
            ))}
          </ol>
        )}
      </Surface>

      <Surface tone="snow" padding="md">
        <h2 className={styles.sectionTitle}>Event log</h2>
        {state.log.length === 0 ? (
          <p className={styles.help}>Nothing has happened in this run yet.</p>
        ) : (
          <ol className={styles.rows}>
            {state.log.map((entry) => (
              <li key={entry.id} className={styles.row}>
                <span className={styles.rowName}>{contentEventName(entry.type)}</span>
                <span className={styles.rowDetail}>
                  {entry.at} · {ORIGIN_WORDS[entry.origin] ?? entry.origin}
                </span>
              </li>
            ))}
          </ol>
        )}
      </Surface>

      <Surface tone="snow" padding="md">
        <h2 className={styles.sectionTitle}>Execution records</h2>
        {state.execution.length === 0 ? (
          <p className={styles.help}>No execution records yet.</p>
        ) : (
          <ol className={styles.rows}>
            {state.execution.map((record) => (
              <li key={record.id} className={styles.row}>
                <span className={styles.rowName}>{KIND_WORDS[record.kind] ?? record.kind}</span>
                <span className={styles.rowDetail}>
                  {record.at}
                  {record.contact_id ? ` · ${record.contact_id}` : ''}
                  {record.reason ? ` · ${record.reason.replaceAll('_', ' ')}` : ''}
                </span>
              </li>
            ))}
          </ol>
        )}
      </Surface>

      <Surface tone="snow" padding="md">
        <h2 className={styles.sectionTitle}>Snapshots and replay</h2>
        <p className={styles.help}>
          {run.checkpoints.length === 0
            ? 'No checkpoints yet. One is taken automatically every 25 events.'
            : `${run.checkpoints.length} checkpoint${run.checkpoints.length === 1 ? '' : 's'}.`}
        </p>
        {run.checkpoints.length > 0 && (
          <ol className={styles.rows}>
            {run.checkpoints.map((point) => (
              <li key={point.id} className={styles.row}>
                <span className={styles.rowName}>{point.label}</span>
                <span className={styles.rowDetail}>
                  {point.at} · after {point.log_length} events
                </span>
              </li>
            ))}
          </ol>
        )}
        <div className={styles.controls}>
          <Button
            variant="secondary"
            onClick={() => {
              markCheckpoint(run, 'marked here').then(store).catch(logFailure);
            }}
          >
            Take a checkpoint
          </Button>
          <Button
            variant="secondary"
            disabled={state.log.length === 0}
            onClick={() => operate((current) => rewind(scenario, current, 1))}
          >
            Step back one event
          </Button>
          <Button
            variant="secondary"
            onClick={() => {
              setProblem(null);
              try {
                const replayed = replay(scenario, state.log, { run_id: state.run_id });
                setReplayResult(
                  historyHash(replayed) === historyHash(state)
                    ? 'Replay reproduced this run exactly.'
                    : 'Replay did not match this run.',
                );
              } catch (error) {
                setProblem(describe(error));
              }
            }}
          >
            Replay this run
          </Button>
          <Button
            variant="secondary"
            onClick={() => {
              resetStoredRun(scenario, state.run_id).then(store).catch(logFailure);
              setReplayResult(null);
            }}
          >
            Reset to the start
          </Button>
        </div>
        {replayResult && (
          <p className={styles.help} role="status" data-testid="replay-result">
            {replayResult}
          </p>
        )}
      </Surface>
    </Stack>
  );
}
