// Master §142: fifteen independent cases. Test titles are exact evidence references, not snapshots.
const row = (
  id,
  name,
  file,
  tests,
  setup,
  expected,
  limitation = 'Controlled fixture; not physical-device or live-provider certification.',
) => ({ id, name, file, tests, setup, expected, limitation });
export const ADVERSARIAL_CASES = [
  row(
    'ADV-01',
    'offline mid-exercise',
    'apps/web/src/exercise/exercise.test.tsx',
    ['a device that works offline syncs its attempt, and the other device agrees'],
    'Complete a real objective attempt without network; reconnect two isolated local databases.',
    'Attempt/evidence queues locally, syncs once and yields matching mastery on the second device.',
  ),
  row(
    'ADV-02',
    'refresh mid-simulation',
    'apps/web/src/simulator/simulator.test.ts',
    [
      'brings back the run, its history, its clock and its queue',
      'does not fire an event twice merely because the page reloaded',
    ],
    'Save an advanced run with a pending event, then load fresh state and continue.',
    'Clock, history, random state and pending queue survive; scheduled events fire once.',
  ),
  row(
    'ADV-03',
    'duplicate events',
    'packages/simulator-core/test/regression.test.ts',
    ['TAG-001 executes real simulator behaviour', 'ENROLL-001 executes real simulator behaviour'],
    'Repeat a tag-add and an active workflow enrolment with re-entry disabled.',
    'No duplicate tag or active enrolment; explicit skip/exit reason. Distinct completed bookings remain distinct events.',
    'Domain duplicate boundaries, not a claim that all separate legitimate events are globally deduplicated.',
  ),
  row(
    'ADV-04',
    'missing phone',
    'packages/simulator-core/test/regression.test.ts',
    ['MSG-001 executes real simulator behaviour'],
    'Send an SMS to the phone-less fixture contact.',
    'No outbound message; action_skipped records missing_phone.',
  ),
  row(
    'ADV-05',
    'missing email',
    'packages/simulator-core/test/regression.test.ts',
    ['MSG-004 executes real simulator behaviour'],
    'Create a contact with a phone but no email, then send email.',
    'No conversation/message or sent-count increment; explicit missing_email.',
  ),
  row(
    'ADV-06',
    'cancelled appointment during wait',
    'packages/simulator-core/test/calendar.test.ts',
    ['enrols the cancellation workflow on APPOINTMENT_CANCELLED and exits the reminder'],
    'Cancel an appointment while its appointment-scoped reminder is waiting.',
    'Exit the reminder before starting cancellation recovery, preserving the cancelled appointment and trigger attribution.',
  ),
  row(
    'ADV-07',
    'timezone change',
    'packages/simulator-core/test/clock.test.ts',
    [
      'ignores the machine timezone: the same scenario reads the same anywhere',
      'adds a day as a calendar day, keeping the wall-clock reading across a DST change',
      'refuses an unknown timezone rather than falling back to the device',
    ],
    'Render the authored instant in Tokyo; advance over Chicago DST; supply an invalid zone.',
    'Preserve the absolute instant and intended local-day semantics; reject invalid zones instead of silently using the device.',
  ),
  row(
    'ADV-08',
    'AI timeout',
    'worker/src/ai/gateway.test.ts',
    [
      'provider timeout is bounded and sanitized',
      'preserves conservative reservation when provider outcome is unknown',
    ],
    'Hold a controlled transport until the abort deadline; simulate unknown provider billing.',
    'Bounded sanitized timeout and conservative reservation, without invented success or blind retry.',
  ),
  row(
    'ADV-09',
    'AI budget exhausted',
    'worker/src/ai/gateway.test.ts',
    [
      'atomic reservations refuse concurrent over-budget calls',
      'protects Off and missing-secret routes without invoking provider',
    ],
    'Reserve the remaining budget while a controlled first request is pending; try a second request and AI Off.',
    'Refuse the over-budget request before provider invocation; Off remains protected.',
  ),
  row(
    'ADV-10',
    'ElevenLabs failure',
    'worker/src/voice/voice.test.ts',
    [
      'sanitizes provider HTTP 503',
      'sanitizes timeouts without retrying',
      'fails cleanly without a secret when the asset is absent',
    ],
    'Controlled ElevenLabs 503, never-resolving response and absent configuration.',
    'Sanitized failure, bounded timeout and no automatic repeat purchase or false ready asset.',
  ),
  row(
    'ADV-11',
    'transcription failure',
    'apps/web/src/call/pipeline.test.ts',
    [
      'retries uploaded audio without uploading again, keeps failures recoverable and survives database reopen',
    ],
    'Reopen local recording storage; transcription returns controlled 503, then succeeds on explicit retry.',
    'Keep the recovery Blob; retry transcription without uploading again, and do not invent a transcript.',
  ),
  row(
    'ADV-12',
    'sync conflict',
    'apps/web/src/data/sync/engine.test.ts',
    [
      'stores divergent snapshot edits as a conflict and resolves either way (SYNC-009)',
      'can also keep the server version of a conflict',
    ],
    'Two devices edit one synchronized note differently.',
    'Preserve both versions pending a choice; explicit local or server selection converges.',
  ),
  row(
    'ADV-13',
    'second device',
    'apps/web/src/exercise/exercise.test.tsx',
    ['two attempts made on two devices are two facts, never merged'],
    'Link two databases and make separate real attempts; exchange multiple sync rounds.',
    'Keep both immutable attempts/evidence and stable counts instead of overwriting or duplicating facts.',
  ),
  row(
    'ADV-14',
    'extreme values',
    'packages/simulator-core/test/advanced-labs.test.ts',
    [
      'refuses malformed amounts, mutable prices, dangling references, disabled links and repeated attempts',
    ],
    'Submit negative, zero, fractional, NaN, Infinity and out-of-range price values, repeated checkout and invalid references.',
    'Refuse invalid values/duplicates without manufactured revenue or mutated accepted prices.',
  ),
  row(
    'ADV-15',
    'malformed scenario data',
    'packages/simulator-core/test/workflow.test.ts',
    [
      'rejects duplicate entity ids',
      'rejects a dangling contact reference',
      'rejects an impossible timestamp',
      'rejects an invalid timezone',
      'throws with every problem listed, rather than skipping the bad ones',
    ],
    'Supply duplicate identities, dangling references, impossible time/zone and a multi-error scenario.',
    'Structured validation rejects the scenario before simulation; no skipped errors or fake runnable state.',
  ),
];
