// Learner route families, including real detail/runner states. Shared by a11y and layout review.
export const SCREEN_MATRIX = [
  ['home', '/'],
  ['campaign', '/campaign'],
  ['skills', '/skills'],
  ['skill-detail', '/skills/SK-STRATEGIZE-funnel-math'],
  ['academy', '/academy/LU-funnel-math-basics'],
  ['academy-connect', '/academy/LU-connect-webhooks'],
  ['exercise', '/exercise/EX-ARCHITECTURE_DECISION-treatment-interest'],
  ['exercise-build', '/exercise/EX-BUILD_IT-no-show-recovery'],
  ['crm', '/crm'],
  ['crm-companies', '/crm?area=companies'],
  ['workflow', '/workflow'],
  ['funnel', '/funnel'],
  ['calendar', '/calendar'],
  ['reporting', '/reporting'],
  ['payments', '/payments'],
  ['incident', '/incident'],
  ['conversations', '/conversations'],
  ['clients', '/clients'],
  ['client-detail', '/clients/CL-glowhaus-medspa'],
  ['portfolio', '/portfolio'],
  ['field-ready', '/field-ready'],
  ['playground', '/playground'],
  ['ai-settings', '/settings/ai'],
  ['sync-restore', '/sync'],
  ['search', '/search'],
  ['search-results', '/search#q=webhook'],
];
