/**
 * Node entry: reads `content/` from disk, compiles it, and manages the version lock.
 * Browser code imports `@bloomlab/content-schema` (schemas and types) — never this file.
 */
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';

import { stringify } from 'yaml';

import type { ContentBundle } from './bundle.ts';
import {
  ContentBuildError,
  checkLock,
  compileSources,
  formatIssue,
  formatIssues,
  validateSources,
  type CompileOptions,
  type CompileResult,
} from './compile/compile.ts';
import {
  renderContentCoverage,
  renderFreshness,
  renderGhlCoverage,
  renderSummary,
} from './compile/reports.ts';
import {
  LOCK_PATH,
  hashSources,
  countSourceFiles,
  type ContentSources,
} from './compile/sources.ts';

export type { ContentSources, CompileOptions, CompileResult };
export {
  ContentBuildError,
  checkLock,
  compileSources,
  formatIssue,
  formatIssues,
  validateSources,
  hashSources,
};
export { renderContentCoverage, renderFreshness, renderGhlCoverage, renderSummary };

/** Reads every file under `rootDir` into memory (paths relative, POSIX separators). */
export async function readContentDir(rootDir: string): Promise<ContentSources> {
  const files: Record<string, string> = {};
  async function walk(dir: string): Promise<void> {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!entry.name.startsWith('.')) await walk(full);
      } else if (entry.isFile()) {
        files[relative(rootDir, full).split(sep).join('/')] = await readFile(full, 'utf8');
      }
    }
  }
  await walk(rootDir);
  return { files };
}

export async function validateContentDir(
  rootDir: string,
  options: CompileOptions = {},
): Promise<CompileResult> {
  return validateSources(await readContentDir(rootDir), options);
}

export async function compileContentDir(
  rootDir: string,
  options: CompileOptions = {},
): Promise<ContentBundle> {
  return compileSources(await readContentDir(rootDir), options);
}

/** Writes `content.lock.yaml` for the current sources (after a successful compile). */
export async function writeLock(
  rootDir: string,
): Promise<{ content_version: string; content_hash: string; files: number }> {
  const sources = await readContentDir(rootDir);
  const bundle = await compileSources(sources);
  const lock = {
    content_version: bundle.content_version,
    content_hash: hashSources(sources),
    files: countSourceFiles(sources),
  };
  await writeFile(
    join(rootDir, LOCK_PATH),
    `# Generated by \`npm run content:lock\` — do not edit. Records which sources content_version describes.\n${stringify(lock)}`,
    'utf8',
  );
  return lock;
}

/** Writes the bundle and the Markdown reports into `outDir` (git-ignored `.content/`). */
export async function writeReports(bundle: ContentBundle, outDir: string): Promise<string[]> {
  await mkdir(outDir, { recursive: true });
  const outputs: [string, string][] = [
    ['bundle.json', JSON.stringify(bundle, null, 2)],
    ['coverage-content.md', renderContentCoverage(bundle)],
    ['coverage-ghl.md', renderGhlCoverage(bundle)],
    ['freshness.md', renderFreshness(bundle)],
    ['summary.txt', renderSummary(bundle)],
  ];
  for (const [name, text] of outputs) await writeFile(join(outDir, name), text, 'utf8');
  return outputs.map(([name]) => join(outDir, name));
}
